.ORIG x4000
START
    SOME_DATA	    .FILL xFE06
    SOME_MORE_DATA	.FILL #12
    EVEN_MORE_DATA
        .FILL xDEAD
        .FILL xBEEF
    LD R0, SOME_DATA
    LD R1, SOME_MORE_DATA
    LD R2, EVEN_MORE_DATA
.END