#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd "$SCRIPT_DIR"

function error {
    echo -e >&2 "\033[31m${1}\033[0m";
    exit 1;
}

function notice {
    local msg="$1"
    shift
    echo -e "$@" >&2 "\033[33m${msg}\033[0m" ;
}

function ensure_env {
    command -v git >/dev/null 2>&1 || error "Please install git"
}

function cmd_test {
    cargo test
    wasm-pack test --node
    echo "✓ Done"
}

function cmd_usage {
    echo "Usage";
}

function run-single-testcase {
    local result
    local exitcode
    local bin="../target/debug/lc3as"

    local file="$1"
    shift
    local additionalArguments="$@"

    notice "Checking '$file' " -n

    set +e
    result="$("${bin}" "$file" 2>&1; exit $?)"
    exitcode=$?
    set -e

    if (( $exitcode == 0 )); then
        echo "✅"
    else
        echo "❌"
    fi
}

function cmd_testcases {
    files="$(find testcases/simple -name '*.asm')"
    cargo build
    for file in ${files}; do
      run-single-testcase "${file}"
    done
}

ensure_env

command=""
if (( $# > 0 )); then
    command="${1}"
    shift
fi

case "${command}" in
    test) cmd_test "$@" ;;
    testcases) cmd_testcases ;;
    *) cmd_usage
esac
