[package]
name = "hello_world"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
clap = "2.32.0"
termios = "0.3.1"

log = "0.4"
pretty_env_logger = "0.4"

lc3_assembler = { path = "../assembler" }